# ==============================================================
# GENERATED BY FORGE CLI — DO NOT EDIT OUTSIDE THE MARKED BLOCK
# Source: forge_demo_silver.forge.ts  |  Layer: silver
# Regenerate: forge generate --job forge_demo_silver
# CI check:   forge generate --check --job forge_demo_silver
# ==============================================================
# ── FORGE:LOCKED:START:HEADER ──
"""
Clean and deduplicate retail orders bronze partition into the silver layer

Layer:     silver
Table:     lakehouse.silver.forgedemo
Partition: __date = DD_MM_YYYY_HH derived from PARTITION_DATE
Schedule:  triggered (no schedule)
Params:
  PARTITION_DATE: string (default: ) — Partition date (yyyy-MM-dd) — set by Airflow data_interval_start
  PARTITION_HOUR: int (default: 0) — Partition hour (0–23) — 0 when date column has no time component
  RESTATE: bool (default: false) — Set true to restate partition even if tracker already exists
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from pyspark.sql import functions as F

from forge_sdk import ForgeJob

try:
    from forge_dq import track
except ImportError:
    import functools

    def track(**kwargs):  # type: ignore[misc]
        """No-op fallback when forge_dq is not installed."""
        def decorator(fn):
            @functools.wraps(fn)
            def wrapper(*args, **kw):
                return fn(*args, **kw)
            return wrapper
        return decorator

# ── FORGE:LOCKED:END:HEADER ──

# ── FORGE:LOCKED:START:HEADER ──
# ---------------------------------------------------------------------------
# Parameters — auto-injected: PARTITION_DATE, PARTITION_HOUR, RESTATE
# ---------------------------------------------------------------------------
FORGE_ENV = os.environ.get("FORGE_ENV", "dev")

PARTITION_DATE = os.environ.get("PARTITION_DATE", "")  # Partition date (yyyy-MM-dd) — set by Airflow data_interval_start
PARTITION_HOUR = int(os.environ.get("PARTITION_HOUR", "0"))  # Partition hour (0–23) — 0 when date column has no time component
RESTATE = os.environ.get("RESTATE", "false").lower() in ("1", "true", "yes")  # Set true to restate partition even if tracker already exists
# ── FORGE:LOCKED:END:HEADER ──


class ForgeDemoSilver(ForgeJob):
    """Clean and deduplicate retail orders bronze partition into the silver layer"""

    # ── FORGE:LOCKED:START:HELPERS ──
    def _tracker_path(self) -> str:
        """ADLS path for this partition's tracker file."""
        _dt = datetime.strptime(PARTITION_DATE, "%Y-%m-%d")
        _date_key = f"{_dt.day:02d}_{_dt.month:02d}_{_dt.year}_{PARTITION_HOUR:02d}"
        return (
            f"abfss://silver@{self.storage}/Demo/Event/Analytics/Demo/ForgeDemo/1/ForgeDemoEvents/_tracker"
            f"/{_date_key}/tracker.json"
        )

    def _tracker_exists(self) -> bool:
        """Return True if this partition's tracker already exists in ADLS."""
        try:
            _path = self._tracker_path()
            _jvm  = self.spark.sparkContext._jvm
            _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
            _p    = _jvm.org.apache.hadoop.fs.Path(_path)
            return bool(_p.getFileSystem(_conf).exists(_p))
        except Exception:
            return False

    def setup(self) -> None:
        if not RESTATE and self._tracker_exists():
            self.log.info(
                "partition_complete skipping table=lakehouse.silver.forgedemo "
                "RESTATE=false — pass RESTATE=true to force rerun",
            )
            raise SystemExit(0)
        if RESTATE:
            self.log.info("restatement_mode table=lakehouse.silver.forgedemo tracker=%s", self._tracker_path())
    # ── FORGE:LOCKED:END:HELPERS ──

    def run(self) -> None:
        # ── FORGE:LOCKED:START:SOURCE ──
        src_path = f"abfss://bronze@{self.storage}/Demo/Event/Internal/Demo/ForgeDemo/1/ForgeDemoBronze"
        raw = (
            self.spark.read
            .format("delta")
            .load(src_path)
        )
        self.log.info("source_read path=%s", src_path)
        # ── FORGE:LOCKED:END:SOURCE ──

        # ╔══════════════════════════════════════════╗
        # ║  EDIT THIS BLOCK — business logic only   ║
        # ╚══════════════════════════════════════════╝
        # ── FORGE:BUSINESS_LOGIC:START ──
        df = raw  # TODO: transform raw → df
        # ── FORGE:BUSINESS_LOGIC:END ──
        # ════════════════════════════════════════════

        # ── FORGE:LOCKED:START:WRITE ──
        _row_count = df.count()
        self.log.info("rows_to_write count=%d", _row_count)
        if _row_count == 0:
            self.log.warning("empty_partition_skipping table=lakehouse.silver.forgedemo")
            return

        # Build __date partition key: DD_MM_YYYY_HH
        _dt = datetime.strptime(PARTITION_DATE, "%Y-%m-%d")
        _date_key = f"{_dt.day:02d}_{_dt.month:02d}_{_dt.year}_{PARTITION_HOUR:02d}"
        df = df.withColumn("__date", F.lit(_date_key))

        @track(
            dataset="lakehouse.silver.forgedemo",
            rules="orchestration/dq/rules/forge_demo_silver.yaml",
            fail_fast=True,
        )
        def _write() -> None:
            (
                df.write
                .format("delta")
                .mode("overwrite")
                .option("overwriteSchema", "true")
                .option("replaceWhere", f"__date = '{_date_key}'")
                .partitionBy("__date")
                .saveAsTable("lakehouse.silver.forgedemo")
            )

        _write()

        self.log.info("write_complete table=lakehouse.silver.forgedemo rows=%d", _row_count)

        # Write tracker — source of truth for run history and downstream dependencies
        _tracker = {
            "version":      "v1",
            "job":          self.__class__.__name__,
            "table":        "lakehouse.silver.forgedemo",
            "partition":    {"date": _date_key},
            "status":       "success",
            "rows_written": _row_count,
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "forge_env":    FORGE_ENV,
        }
        _tracker_path = self._tracker_path()
        _jvm  = self.spark.sparkContext._jvm
        _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
        _p    = _jvm.org.apache.hadoop.fs.Path(_tracker_path)
        _out  = _p.getFileSystem(_conf).create(_p, True)
        _out.write(bytearray(json.dumps(_tracker, indent=2).encode("utf-8")))
        _out.close()
        self.log.info("tracker_written path=%s rows=%d", _tracker_path, _row_count)
        # ── FORGE:LOCKED:END:WRITE ──


if __name__ == "__main__":
    ForgeDemoSilver().execute()
