# ==============================================================
# GENERATED BY FORGE CLI — DO NOT EDIT OUTSIDE THE MARKED BLOCK
# Source: nyc_taxi_bronze.forge.ts  |  Layer: bronze
# Regenerate: forge generate --job nyc_taxi_bronze
# CI check:   forge generate --check --job nyc_taxi_bronze
# ==============================================================
# ── FORGE:LOCKED:START:HEADER ──
"""
Daily ingestion of NYC TLC Yellow Taxi trip data from Azure Open Datasets

Layer:     bronze
Table:     lakehouse.bronze.nyctaxi
Partition: __year/__month/__day/__hour from pickup_datetime (hour=PARTITION_HOUR, default 0)
Schedule:  0 2 * * *
Params:
  TAXI_TYPE: string (default: yellow) — yellow | green | fhv | hvfhv
  DATA_SOURCE_NAME: string (default: nyc-taxi-yellow) — name registered in portal data_sources
  PARTITION_DATE: string (default: ) — Partition date (yyyy-MM-dd) — set by Airflow data_interval_start
  PARTITION_HOUR: int (default: 0) — Partition hour (0–23) — 0 when date column has no time component
  RESTATE: bool (default: false) — Set true to restate partition even if tracker already exists

Source: wasbs://nyctlc@azureopendatastorage.blob.core.windows.net/yellow/
        Azure Open Datasets — public parquet, partitioned by puYear/puMonth.
        Anonymous access configured via sparkConf in the DAG SparkApplication spec.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from pyspark.sql import functions as F

from forge_sdk import ForgeJob

# ── FORGE:LOCKED:END:HEADER ──

# ── FORGE:LOCKED:START:HEADER ──
FORGE_ENV = os.environ.get("FORGE_ENV", "dev")
TAXI_TYPE = os.environ.get("TAXI_TYPE", "yellow")
DATA_SOURCE_NAME = os.environ.get("DATA_SOURCE_NAME", "nyc-taxi-yellow")
PARTITION_DATE = os.environ.get("PARTITION_DATE", "")
PARTITION_HOUR = int(os.environ.get("PARTITION_HOUR", "0"))
RESTATE = os.environ.get("RESTATE", "false").lower() in ("1", "true", "yes")
# ── FORGE:LOCKED:END:HEADER ──


class NycTaxiBronze(ForgeJob):
    """Daily ingestion of NYC TLC Yellow Taxi trip data from Azure Open Datasets"""

    # ── FORGE:LOCKED:START:HELPERS ──
    def _tracker_path(self) -> str:
        _year, _month, _day = (int(x) for x in PARTITION_DATE.split("-"))
        return (
            f"abfss://bronze@{self.storage}/Transport/Trip/Internal/Rideshare/NycTaxi/1/NycTaxiBronze/_tracker"
            f"/{_year}/{_month}/{_day}/{PARTITION_HOUR}/tracker.json"
        )

    def _tracker_exists(self) -> bool:
        try:
            _path = self._tracker_path()
            _jvm  = self.spark.sparkContext._jvm
            _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
            _p    = _jvm.org.apache.hadoop.fs.Path(_path)
            return bool(_p.getFileSystem(_conf).exists(_p))
        except Exception:
            return False

    def setup(self) -> None:
        if not RESTATE and self._tracker_exists():
            self.log.info(
                "partition_complete skipping table=lakehouse.bronze.nyctaxi "
                "RESTATE=false — pass RESTATE=true to force rerun",
            )
            raise SystemExit(0)
        if RESTATE:
            self.log.info("restatement_mode table=lakehouse.bronze.nyctaxi tracker=%s", self._tracker_path())
    # ── FORGE:LOCKED:END:HELPERS ──

    def _lookup_source(self) -> dict:
        """Fetch source config from portal data_sources registry via Postgres."""
        import ssl
        try:
            import asyncio
            import asyncpg  # type: ignore
            from azure.identity import WorkloadIdentityCredential  # type: ignore

            pg_host = os.environ.get("PG_HOST", "")
            pg_user = os.environ.get("PG_USER", "")
            if not pg_host or not pg_user:
                self.log.info("source_lookup_skipped pg_host not set — using defaults")
                return {}

            cred = WorkloadIdentityCredential()
            token = cred.get_token("https://ossrdbms-aad.database.windows.net/.default").token
            ssl_ctx = ssl.create_default_context()

            async def _fetch():
                conn = await asyncpg.connect(
                    host=pg_host, port=5432, database="portal",
                    user=pg_user, password=token, ssl=ssl_ctx,
                )
                try:
                    row = await conn.fetchrow(
                        "SELECT config FROM data_sources WHERE name = $1", DATA_SOURCE_NAME
                    )
                    return dict(row["config"]) if row else {}
                finally:
                    await conn.close()

            return asyncio.get_event_loop().run_until_complete(_fetch())
        except Exception as exc:
            self.log.warning("source_lookup_failed error=%s — using defaults", str(exc))
            return {}

    def run(self) -> None:
        # ── FORGE:LOCKED:START:SOURCE ──
        _year, _month, _day = (int(x) for x in PARTITION_DATE.split("-"))

        # Resolve connection details from the registered data source in portal.
        # Falls back to defaults (Azure Open Datasets) if Postgres is unavailable.
        _src_config = self._lookup_source()
        _account   = _src_config.get("account", "azureopendatastorage")
        _container = _src_config.get("container", "nyctlc")
        _base_path = _src_config.get("base_path", f"/{TAXI_TYPE}").rstrip("/")

        # Azure Open Datasets — public blob storage, partitioned by puYear/puMonth.
        # Anonymous access pre-configured via sparkConf in DAG spec:
        #   fs.azure.account.auth.type.azureopendatastorage.blob.core.windows.net = Anonymous
        src_path = (
            f"wasbs://{_container}@{_account}.blob.core.windows.net"
            f"{_base_path}/puYear={_year}/puMonth={_month}/"
        )
        raw = (
            self.spark.read
            .option("mergeSchema", "true")
            .parquet(src_path)
        )
        self.log.info("source_read path=%s datasource=%s account=%s", src_path, DATA_SOURCE_NAME, _account)
        # ── FORGE:LOCKED:END:SOURCE ──

        # ╔══════════════════════════════════════════╗
        # ║  EDIT THIS BLOCK — business logic only   ║
        # ╚══════════════════════════════════════════╝
        # ── FORGE:BUSINESS_LOGIC:START ──

        # Filter to just this partition day (Open Datasets files are month-level)
        partition_dt = PARTITION_DATE  # yyyy-MM-dd
        df = raw.filter(
            F.to_date(F.col("tpepPickupDatetime")) == F.lit(partition_dt)
        )

        # Add audit columns
        df = (
            df
            .withColumn("taxi_type", F.lit(TAXI_TYPE))
            .withColumn("data_source", F.lit(DATA_SOURCE_NAME))
            .withColumn("_source", F.lit(f"azure-open-datasets/nyctlc/{TAXI_TYPE}"))
            .withColumn("_ingested_at", F.current_timestamp())
        )

        # ── FORGE:BUSINESS_LOGIC:END ──
        # ════════════════════════════════════════════

        # ── FORGE:LOCKED:START:WRITE ──
        _row_count = df.count()
        self.log.info("rows_to_write count=%d", _row_count)
        if _row_count == 0:
            self.log.warning("empty_partition_skipping table=lakehouse.bronze.nyctaxi date=%s", PARTITION_DATE)
            return

        df = (
            df
            .withColumn("__year",  F.lit(_year))
            .withColumn("__month", F.lit(_month))
            .withColumn("__day",   F.lit(_day))
            .withColumn("__hour",  F.lit(PARTITION_HOUR))
        )

        (
            df.write
            .format("delta")
            .mode("overwrite")
            .option("overwriteSchema", "true")
            .option("replaceWhere", f"__year = {_year} AND __month = {_month} AND __day = {_day} AND __hour = {PARTITION_HOUR}")
            .partitionBy("__year", "__month", "__day", "__hour")
            .saveAsTable("lakehouse.bronze.nyctaxi")
        )

        self.log.info("write_complete table=lakehouse.bronze.nyctaxi rows=%d", _row_count)

        _tracker = {
            "version":      "v1",
            "job":          self.__class__.__name__,
            "table":        "lakehouse.bronze.nyctaxi",
            "partition":    {"year": _year, "month": _month, "day": _day, "hour": PARTITION_HOUR},
            "source":       DATA_SOURCE_NAME,
            "taxi_type":    TAXI_TYPE,
            "status":       "success",
            "rows_written": _row_count,
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "forge_env":    FORGE_ENV,
        }
        _tracker_path = self._tracker_path()
        _jvm  = self.spark.sparkContext._jvm
        _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
        _p    = _jvm.org.apache.hadoop.fs.Path(_tracker_path)
        _out  = _p.getFileSystem(_conf).create(_p, True)
        _out.write(bytearray(json.dumps(_tracker, indent=2).encode("utf-8")))
        _out.close()
        self.log.info("tracker_written path=%s rows=%d", _tracker_path, _row_count)
        # ── FORGE:LOCKED:END:WRITE ──


if __name__ == "__main__":
    NycTaxiBronze().execute()
