# ==============================================================
# GENERATED BY FORGE CLI — DO NOT EDIT OUTSIDE THE MARKED BLOCK
# Source: nyc_taxi_gold.forge.ts  |  Layer: gold
# Regenerate: forge generate --job nyc_taxi_gold
# CI check:   forge generate --check --job nyc_taxi_gold
# ==============================================================
# ── FORGE:LOCKED:START:HEADER ──
"""
NYC Yellow Taxi gold aggregations

Layer:     gold
Tables:    lakehouse.gold.nyctaxi_daily_summary
           lakehouse.gold.nyctaxi_hourly_demand
           lakehouse.gold.nyctaxi_zone_stats
           lakehouse.gold.nyctaxi_payment_summary
Partition: __date = yyyy-MM-dd
Schedule:  triggered (no schedule)
Params:
  PARTITION_DATE: string (default: ) — Partition date (yyyy-MM-dd)
  GOLD_TABLE: string [required] — daily_summary | hourly_demand | zone_stats | payment_summary
  RESTATE: bool (default: false)
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from pyspark.sql import DataFrame, functions as F

from forge_sdk import ForgeJob

# ── FORGE:LOCKED:END:HEADER ──

# ── FORGE:LOCKED:START:HEADER ──
FORGE_ENV = os.environ.get("FORGE_ENV", "dev")
PARTITION_DATE = os.environ.get("PARTITION_DATE", "")
PARTITION_HOUR = int(os.environ.get("PARTITION_HOUR", "0"))
GOLD_TABLE = os.environ["GOLD_TABLE"]  # daily_summary | hourly_demand | zone_stats | payment_summary
RESTATE = os.environ.get("RESTATE", "false").lower() in ("1", "true", "yes")

_TABLE_MAP = {
    "daily_summary":   "lakehouse.gold.nyctaxi_daily_summary",
    "hourly_demand":   "lakehouse.gold.nyctaxi_hourly_demand",
    "zone_stats":      "lakehouse.gold.nyctaxi_zone_stats",
    "payment_summary": "lakehouse.gold.nyctaxi_payment_summary",
}
_HMS_TABLE = _TABLE_MAP[GOLD_TABLE]
# ── FORGE:LOCKED:END:HEADER ──


class NycTaxiGold(ForgeJob):
    """NYC Yellow Taxi gold aggregations"""

    # ── FORGE:LOCKED:START:HELPERS ──
    def _tracker_path(self) -> str:
        return (
            f"abfss://gold@{self.storage}/Transport/Trip/Analytics/Rideshare/NycTaxi/1/NycTaxiMetrics/_tracker"
            f"/{GOLD_TABLE}/{PARTITION_DATE}/tracker.json"
        )

    def _tracker_exists(self) -> bool:
        try:
            _path = self._tracker_path()
            _jvm  = self.spark.sparkContext._jvm
            _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
            _p    = _jvm.org.apache.hadoop.fs.Path(_path)
            return bool(_p.getFileSystem(_conf).exists(_p))
        except Exception:
            return False

    def setup(self) -> None:
        if not RESTATE and self._tracker_exists():
            self.log.info(
                "partition_complete skipping table=%s RESTATE=false", _HMS_TABLE,
            )
            raise SystemExit(0)
        if RESTATE:
            self.log.info("restatement_mode table=%s tracker=%s", _HMS_TABLE, self._tracker_path())
    # ── FORGE:LOCKED:END:HELPERS ──

    def run(self) -> None:
        # ── FORGE:LOCKED:START:SOURCE ──
        src_path = f"abfss://silver@{self.storage}/Transport/Trip/Analytics/Rideshare/NycTaxi/1/NycTaxiTrips"
        silver = (
            self.spark.read
            .format("delta")
            .load(src_path)
            .filter(F.col("__date") == PARTITION_DATE)
        )
        self.log.info("source_read path=%s partition=%s", src_path, PARTITION_DATE)
        # ── FORGE:LOCKED:END:SOURCE ──

        # ╔══════════════════════════════════════════╗
        # ║  EDIT THIS BLOCK — business logic only   ║
        # ╚══════════════════════════════════════════╝
        # ── FORGE:BUSINESS_LOGIC:START ──

        agg: DataFrame

        if GOLD_TABLE == "daily_summary":
            agg = silver.groupBy("pickup_date").agg(
                F.count("*").alias("trip_count"),
                F.round(F.sum("fare_amount"), 2).alias("total_fare"),
                F.round(F.sum("total_amount"), 2).alias("total_revenue"),
                F.round(F.avg("fare_amount"), 2).alias("avg_fare"),
                F.round(F.avg("tip_amount"), 2).alias("avg_tip"),
                F.round(F.avg("trip_distance_miles"), 2).alias("avg_distance_miles"),
                F.round(F.avg("trip_duration_minutes"), 2).alias("avg_duration_minutes"),
                F.round(F.avg("passenger_count"), 2).alias("avg_passengers"),
                F.round(F.sum("trip_distance_miles"), 2).alias("total_miles"),
            )

        elif GOLD_TABLE == "hourly_demand":
            agg = silver.groupBy("pickup_date", "pickup_hour").agg(
                F.count("*").alias("trip_count"),
                F.round(F.avg("fare_amount"), 2).alias("avg_fare"),
                F.round(F.avg("trip_duration_minutes"), 2).alias("avg_duration_minutes"),
                F.round(F.sum("fare_amount"), 2).alias("total_fare"),
            ).orderBy("pickup_date", "pickup_hour")

        elif GOLD_TABLE == "zone_stats":
            agg = silver.groupBy("pickup_date", "pickup_location_id", "dropoff_location_id").agg(
                F.count("*").alias("trip_count"),
                F.round(F.avg("fare_amount"), 2).alias("avg_fare"),
                F.round(F.avg("trip_distance_miles"), 2).alias("avg_distance_miles"),
                F.round(F.avg("trip_duration_minutes"), 2).alias("avg_duration_minutes"),
                F.round(F.sum("fare_amount"), 2).alias("total_fare"),
            )

        elif GOLD_TABLE == "payment_summary":
            agg = silver.groupBy("pickup_date", "payment_type").agg(
                F.count("*").alias("trip_count"),
                F.round(F.sum("fare_amount"), 2).alias("total_fare"),
                F.round(F.sum("tip_amount"), 2).alias("total_tips"),
                F.round(F.avg("fare_amount"), 2).alias("avg_fare"),
                F.round(F.avg("tip_amount"), 2).alias("avg_tip"),
                F.round(F.sum("total_amount"), 2).alias("total_revenue"),
            )

        else:
            raise ValueError(f"Unknown GOLD_TABLE: {GOLD_TABLE}")

        agg = agg.withColumn("__date", F.lit(PARTITION_DATE))

        # ── FORGE:BUSINESS_LOGIC:END ──
        # ════════════════════════════════════════════

        # ── FORGE:LOCKED:START:WRITE ──
        _row_count = agg.count()
        self.log.info("rows_to_write count=%d table=%s", _row_count, _HMS_TABLE)
        if _row_count == 0:
            self.log.warning("empty_partition_skipping table=%s date=%s", _HMS_TABLE, PARTITION_DATE)
            return

        (
            agg.write
            .format("delta")
            .mode("overwrite")
            .option("overwriteSchema", "true")
            .option("replaceWhere", f"__date = '{PARTITION_DATE}'")
            .partitionBy("__date")
            .saveAsTable(_HMS_TABLE)
        )

        self.log.info("write_complete table=%s rows=%d", _HMS_TABLE, _row_count)

        _tracker = {
            "version":      "v1",
            "job":          self.__class__.__name__,
            "table":        _HMS_TABLE,
            "gold_table":   GOLD_TABLE,
            "partition":    {"date": PARTITION_DATE},
            "status":       "success",
            "rows_written": _row_count,
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "forge_env":    FORGE_ENV,
        }
        _tracker_path = self._tracker_path()
        _jvm  = self.spark.sparkContext._jvm
        _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
        _p    = _jvm.org.apache.hadoop.fs.Path(_tracker_path)
        _out  = _p.getFileSystem(_conf).create(_p, True)
        _out.write(bytearray(json.dumps(_tracker, indent=2).encode("utf-8")))
        _out.close()
        self.log.info("tracker_written path=%s rows=%d", _tracker_path, _row_count)
        # ── FORGE:LOCKED:END:WRITE ──


if __name__ == "__main__":
    NycTaxiGold().execute()
