# ==============================================================
# GENERATED BY FORGE CLI — DO NOT EDIT OUTSIDE THE MARKED BLOCK
# Source: nyc_taxi_bronze.forge.ts  |  Layer: bronze
# Regenerate: forge generate --job nyc_taxi_bronze
# CI check:   forge generate --check --job nyc_taxi_bronze
# ==============================================================
# ── FORGE:LOCKED:START:HEADER ──
"""
Daily ingestion of NYC TLC trip data from Azure Open Datasets, partitioned by pickup date

Layer:     bronze
Table:     lakehouse.bronze.nyc_taxi
Partition: __year/__month/__day/__hour from pickup_datetime (hour=PARTITION_HOUR, default 0)
Schedule:  0 2 * * *
Params:
  TAXI_TYPE: string (default: yellow) — yellow | green | fhv | hvfhv
  PARTITION_DATE: string (default: ) — Partition date (yyyy-MM-dd) — set by Airflow data_interval_start
  PARTITION_HOUR: int (default: 0) — Partition hour (0–23) — 0 when date column has no time component
  RESTATE: bool (default: false) — Set true to restate partition even if tracker already exists
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from pyspark.sql import functions as F

from forge_sdk import ForgeJob

# ── FORGE:LOCKED:END:HEADER ──

# ── FORGE:LOCKED:START:HEADER ──
# ---------------------------------------------------------------------------
# Parameters — auto-injected: PARTITION_DATE, PARTITION_HOUR, RESTATE
# ---------------------------------------------------------------------------
FORGE_ENV = os.environ.get("FORGE_ENV", "dev")

TAXI_TYPE = os.environ.get("TAXI_TYPE", "yellow")  # yellow | green | fhv | hvfhv
PARTITION_DATE = os.environ.get("PARTITION_DATE", "")  # Partition date (yyyy-MM-dd) — set by Airflow data_interval_start
PARTITION_HOUR = int(os.environ.get("PARTITION_HOUR", "0"))  # Partition hour (0–23) — 0 when date column has no time component
RESTATE = os.environ.get("RESTATE", "false").lower() in ("1", "true", "yes")  # Set true to restate partition even if tracker already exists
# ── FORGE:LOCKED:END:HEADER ──


class NycTaxiBronze(ForgeJob):
    """Daily ingestion of NYC TLC trip data from Azure Open Datasets, partitioned by pickup date"""

    # ── FORGE:LOCKED:START:HELPERS ──
    def _tracker_path(self) -> str:
        """ADLS path for this partition's tracker file."""
        _year, _month, _day = (int(x) for x in PARTITION_DATE.split("-"))
        return (
            f"{self.bronze("nyc/taxi/_tracker")}"
            f"/{_year}/{_month}/{_day}/{PARTITION_HOUR}/tracker.json"
        )

    def _tracker_exists(self) -> bool:
        """Return True if this partition's tracker already exists in ADLS."""
        try:
            _path = self._tracker_path()
            _jvm  = self.spark.sparkContext._jvm
            _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
            _p    = _jvm.org.apache.hadoop.fs.Path(_path)
            return bool(_p.getFileSystem(_conf).exists(_p))
        except Exception:
            return False

    def setup(self) -> None:
        if not RESTATE and self._tracker_exists():
            self.log.info(
                "partition_complete skipping table=lakehouse.bronze.nyc_taxi "
                "RESTATE=false — pass RESTATE=true to force rerun",
            )
            raise SystemExit(0)
        if RESTATE:
            self.log.info("restatement_mode table=lakehouse.bronze.nyc_taxi tracker=%s", self._tracker_path())
    # ── FORGE:LOCKED:END:HELPERS ──

    def run(self) -> None:
        # ── FORGE:LOCKED:START:SOURCE ──
        src_path = f"wasbs://nyctlc@azureopendatastore.blob.core.windows.net/{TAXI_TYPE}/*.parquet"
        raw = (
            self.spark.read
            .option("mergeSchema", "true")
            .parquet(src_path)
        )
        self.log.info("source_read path=%s", src_path)
        # ── FORGE:LOCKED:END:SOURCE ──

        # ╔══════════════════════════════════════════╗
        # ║  EDIT THIS BLOCK — business logic only   ║
        # ╚══════════════════════════════════════════╝
        # ── FORGE:BUSINESS_LOGIC:START ──
        df = raw  # TODO: transform raw → df
        # ── FORGE:BUSINESS_LOGIC:END ──
        # ════════════════════════════════════════════

        # ── FORGE:LOCKED:START:WRITE ──
        _row_count = df.count()
        self.log.info("rows_to_write count=%d", _row_count)
        if _row_count == 0:
            self.log.warning("empty_partition_skipping table=lakehouse.bronze.nyc_taxi")
            return

        # Stamp partition columns
        _year, _month, _day = (int(x) for x in PARTITION_DATE.split("-"))
        df = (
            df
            .withColumn("__year",  F.lit(_year))
            .withColumn("__month", F.lit(_month))
            .withColumn("__day",   F.lit(_day))
            .withColumn("__hour",  F.lit(PARTITION_HOUR))
        )

        (
            df.write
            .format("delta")
            .mode("overwrite")
            .option("overwriteSchema", "true")
            .option("replaceWhere", f"__year = {_year} AND __month = {_month} AND __day = {_day} AND __hour = {PARTITION_HOUR}")
            .partitionBy("__year", "__month", "__day", "__hour")
            .saveAsTable("lakehouse.bronze.nyc_taxi")
        )

        self.log.info("write_complete table=lakehouse.bronze.nyc_taxi rows=%d", _row_count)

        # Write tracker — source of truth for run history and downstream dependencies
        _tracker = {
            "version":      "v1",
            "job":          self.__class__.__name__,
            "table":        "lakehouse.bronze.nyc_taxi",
            "partition":    {"year": _year, "month": _month, "day": _day, "hour": PARTITION_HOUR},
            "status":       "success",
            "rows_written": _row_count,
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "forge_env":    FORGE_ENV,
        }
        _tracker_path = self._tracker_path()
        _jvm  = self.spark.sparkContext._jvm
        _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
        _p    = _jvm.org.apache.hadoop.fs.Path(_tracker_path)
        _out  = _p.getFileSystem(_conf).create(_p, True)
        _out.write(bytearray(json.dumps(_tracker, indent=2).encode("utf-8")))
        _out.close()
        self.log.info("tracker_written path=%s rows=%d", _tracker_path, _row_count)
        # ── FORGE:LOCKED:END:WRITE ──


if __name__ == "__main__":
    NycTaxiBronze().execute()
