# ==============================================================
# GENERATED BY FORGE CLI — DO NOT EDIT OUTSIDE THE MARKED BLOCK
# Source: nyc_taxi_gold.forge.ts  |  Layer: gold
# Regenerate: forge generate --job nyc_taxi_gold
# CI check:   forge generate --check --job nyc_taxi_gold
# ==============================================================
# ── FORGE:LOCKED:START:HEADER ──
"""
NYC taxi gold aggregations: daily_summary, hourly_demand, zone_stats, payment_summary

Layer:     gold
Table:     lakehouse.gold.nyctaxi
Partition: __date = DD_MM_YYYY_HH derived from PARTITION_MONTH
Schedule:  triggered (no schedule)
Params:
  PARTITION_YEAR: int (default: 2023)
  PARTITION_MONTH: int (default: 1)
  GOLD_TABLE: string [required] — daily_summary | hourly_demand | zone_stats | payment_summary
  PARTITION_DATE: string (default: ) — Partition date (yyyy-MM-dd) — set by Airflow data_interval_start
  PARTITION_HOUR: int (default: 0) — Partition hour (0–23) — 0 when date column has no time component
  RESTATE: bool (default: false) — Set true to restate partition even if tracker already exists
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from pyspark.sql import functions as F

from forge_sdk import ForgeJob

# ── FORGE:LOCKED:END:HEADER ──

# ── FORGE:LOCKED:START:HEADER ──
# ---------------------------------------------------------------------------
# Parameters — auto-injected: PARTITION_DATE, PARTITION_HOUR, RESTATE
# ---------------------------------------------------------------------------
FORGE_ENV = os.environ.get("FORGE_ENV", "dev")

PARTITION_YEAR = int(os.environ.get("PARTITION_YEAR", "2023"))
PARTITION_MONTH = int(os.environ.get("PARTITION_MONTH", "1"))
GOLD_TABLE = os.environ["GOLD_TABLE"]  # daily_summary | hourly_demand | zone_stats | payment_summary
PARTITION_DATE = os.environ.get("PARTITION_DATE", "")  # Partition date (yyyy-MM-dd) — set by Airflow data_interval_start
PARTITION_HOUR = int(os.environ.get("PARTITION_HOUR", "0"))  # Partition hour (0–23) — 0 when date column has no time component
RESTATE = os.environ.get("RESTATE", "false").lower() in ("1", "true", "yes")  # Set true to restate partition even if tracker already exists
# ── FORGE:LOCKED:END:HEADER ──


class NycTaxiGold(ForgeJob):
    """NYC taxi gold aggregations: daily_summary, hourly_demand, zone_stats, payment_summary"""

    # ── FORGE:LOCKED:START:HELPERS ──
    def _tracker_path(self) -> str:
        """ADLS path for this partition's tracker file."""
        _dt = datetime.strptime(PARTITION_DATE, "%Y-%m-%d")
        _date_key = f"{_dt.day:02d}_{_dt.month:02d}_{_dt.year}_{PARTITION_HOUR:02d}"
        return (
            f"abfss://gold@{self.storage}/Transport/Trip/Analytics/Rideshare/NycTaxi/1/NycTaxiMetrics/_tracker"
            f"/{_date_key}/tracker.json"
        )

    def _tracker_exists(self) -> bool:
        """Return True if this partition's tracker already exists in ADLS."""
        try:
            _path = self._tracker_path()
            _jvm  = self.spark.sparkContext._jvm
            _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
            _p    = _jvm.org.apache.hadoop.fs.Path(_path)
            return bool(_p.getFileSystem(_conf).exists(_p))
        except Exception:
            return False

    def setup(self) -> None:
        if not RESTATE and self._tracker_exists():
            self.log.info(
                "partition_complete skipping table=lakehouse.gold.nyctaxi "
                "RESTATE=false — pass RESTATE=true to force rerun",
            )
            raise SystemExit(0)
        if RESTATE:
            self.log.info("restatement_mode table=lakehouse.gold.nyctaxi tracker=%s", self._tracker_path())
    # ── FORGE:LOCKED:END:HELPERS ──

    def run(self) -> None:
        # ── FORGE:LOCKED:START:SOURCE ──
        src_path = f"abfss://silver@{self.storage}/Transport/Trip/Analytics/Rideshare/NycTaxi/1/NycTaxiTrips"
        raw = (
            self.spark.read
            .format("delta")
            .load(src_path)
        )
        self.log.info("source_read path=%s", src_path)
        # ── FORGE:LOCKED:END:SOURCE ──

        # ╔══════════════════════════════════════════╗
        # ║  EDIT THIS BLOCK — business logic only   ║
        # ╚══════════════════════════════════════════╝
        # ── FORGE:BUSINESS_LOGIC:START ──
        df = raw  # TODO: transform raw → df
        # ── FORGE:BUSINESS_LOGIC:END ──
        # ════════════════════════════════════════════

        # ── FORGE:LOCKED:START:WRITE ──
        _row_count = df.count()
        self.log.info("rows_to_write count=%d", _row_count)
        if _row_count == 0:
            self.log.warning("empty_partition_skipping table=lakehouse.gold.nyctaxi")
            return

        # Build __date partition key: DD_MM_YYYY_HH
        _dt = datetime.strptime(PARTITION_DATE, "%Y-%m-%d")
        _date_key = f"{_dt.day:02d}_{_dt.month:02d}_{_dt.year}_{PARTITION_HOUR:02d}"
        df = df.withColumn("__date", F.lit(_date_key))

        (
            df.write
            .format("delta")
            .mode("overwrite")
            .option("overwriteSchema", "true")
            .option("replaceWhere", f"__date = '{_date_key}'")
            .partitionBy("__date")
            .saveAsTable("lakehouse.gold.nyctaxi")
        )

        self.log.info("write_complete table=lakehouse.gold.nyctaxi rows=%d", _row_count)

        # Write tracker — source of truth for run history and downstream dependencies
        _tracker = {
            "version":      "v1",
            "job":          self.__class__.__name__,
            "table":        "lakehouse.gold.nyctaxi",
            "partition":    {"date": _date_key},
            "status":       "success",
            "rows_written": _row_count,
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "forge_env":    FORGE_ENV,
        }
        _tracker_path = self._tracker_path()
        _jvm  = self.spark.sparkContext._jvm
        _conf = self.spark.sparkContext._jsc.hadoopConfiguration()
        _p    = _jvm.org.apache.hadoop.fs.Path(_tracker_path)
        _out  = _p.getFileSystem(_conf).create(_p, True)
        _out.write(bytearray(json.dumps(_tracker, indent=2).encode("utf-8")))
        _out.close()
        self.log.info("tracker_written path=%s rows=%d", _tracker_path, _row_count)
        # ── FORGE:LOCKED:END:WRITE ──


if __name__ == "__main__":
    NycTaxiGold().execute()
