apiVersion: v1
kind: Service
metadata:
  name: trino-internal
  namespace: trino
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/instance: trino
    app.kubernetes.io/name: trino
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
