apiVersion: v1
kind: Secret
metadata:
  name: hive-metastore-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: hive-metastore
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  db-host: {{ .Values.db.host | quote }}
  db-user: {{ .Values.db.user | quote }}
  db-password: {{ .Values.db.password | quote }}
