apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: trino-auth-proxy
    azure.workload.identity/use: "true"
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
