apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default "spark-connect" }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride | default "spark-connect" }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.nameOverride | default "spark-connect" }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
