"""
forge_sdk.job.dq_gate — Platform-level DQ gate Spark job.

Deployed to ADLS at:
  abfss://code@<storage>.dfs.core.windows.net/spark/jobs/forge_dq_gate.py

Called by the ``dq_gate_<layer>`` SparkKubernetesOperator task generated by
``forge generate``.  Never edit this file in a job repo — it is a platform
artifact managed in DSEngCoreInfra.

Env vars (all injected by the generated DAG):
  LAYER          — bronze | silver | gold
  TABLE          — Hive/Trino table name (e.g. lakehouse.bronze.nyctaxi)
  PARTITION_DATE — yyyy-MM-dd  (filters to the just-written partition)
  RULES_YAML     — base64-encoded YAML of the inline DQ rules from the manifest
  FAIL_FAST      — "true" (default) | "false"
"""
from __future__ import annotations

import base64
import os

import yaml
from pyspark.sql import functions as F

from forge_sdk import ForgeJob
from forge_dq import DQRunner

LAYER          = os.environ.get("LAYER", "bronze")
TABLE          = os.environ.get("TABLE", "")
PARTITION_DATE = os.environ.get("PARTITION_DATE", "")
RULES_YAML_B64 = os.environ.get("RULES_YAML", "")
FAIL_FAST      = os.environ.get("FAIL_FAST", "true").lower() not in ("0", "false", "no")


def _decode_rules(b64: str) -> list[dict]:
    """Decode a base64-encoded YAML rules snippet into a list of rule dicts."""
    if not b64:
        return []
    decoded = base64.b64decode(b64).decode("utf-8")
    parsed = yaml.safe_load(decoded)
    if isinstance(parsed, dict) and "rules" in parsed:
        return parsed["rules"] or []
    return []


class ForgeDQGate(ForgeJob):
    """
    Validates a freshly written partition against inline DQ rules from the manifest.

    Reads the partition from the Hive/Delta table, runs all rules via DQRunner,
    and raises DQCriticalFailureError on any CRITICAL violation when
    FAIL_FAST is true (default).
    """

    def run(self) -> None:
        if not TABLE:
            raise ValueError("TABLE env var is required for forge_dq_gate")

        df = self.spark.table(TABLE)

        # Filter to the partition that was just written so profiling stats
        # reflect this run, not the entire table history.
        if PARTITION_DATE:
            if LAYER == "bronze":
                year, month, day = (int(p) for p in PARTITION_DATE.split("-"))
                df = df.filter(
                    (F.col("__year") == year)
                    & (F.col("__month") == month)
                    & (F.col("__day") == day)
                )
            else:
                df = df.filter(F.col("__date") == F.lit(PARTITION_DATE))

        rules = _decode_rules(RULES_YAML_B64)
        if not rules:
            self.log.warning(
                "dq_gate_no_rules layer=%s table=%s — skipping DQ (RULES_YAML is empty)",
                LAYER,
                TABLE,
            )
            return

        runner = DQRunner(
            self.spark,
            dataset=TABLE,
            rules=rules,
            pipeline_name=f"forge_dq_gate_{LAYER}",
            fail_on_critical=FAIL_FAST,
        )
        report = runner.run(df)
        self.log.info(
            "dq_gate_result layer=%s table=%s status=%s rows=%d critical_failures=%s",
            LAYER,
            TABLE,
            report.overall_status,
            report.rows_written,
            report.critical_failures,
        )
        # DQRunner raises DQCriticalFailureError if fail_on_critical=True (default)
        # and any CRITICAL rule fails — this propagates up and fails the Spark job,
        # which in turn fails the Airflow task and blocks downstream stages.


if __name__ == "__main__":
    ForgeDQGate().execute()
