/**
 * Forge CLI — DQ Rules YAML Generator
 *
 * Produces a skeleton Data Quality rules file for a manifest that has `dq`
 * configured.  The output matches the format used by the Forge DQ framework
 * (forge_dq @track decorator) and mirrors the existing rules files in
 * examples/orchestration/dq/rules/.
 *
 * The generated file is a starting point — engineers are expected to add
 * domain-specific rules before it is committed.
 */
import type { ForgeJobManifest } from "../schema.js";

/**
 * Generate a skeleton DQ YAML rules file from a manifest.
 *
 * @param manifest Validated ForgeJobManifest (must have `dq` set)
 * @returns YAML string ready to write to disk
 */
export function generateDqYaml(manifest: ForgeJobManifest): string {
  const table = manifest.output.table;
  const layer = manifest.layer;
  const { column, granularity } = manifest.partition;

  // For day granularity: one partition column (the date column itself).
  // For hour granularity: four derived partition columns.
  const partitionCols: string[] =
    granularity === "hour"
      ? ["year", "month", "day", "hour"]
      : [column];

  // Build a set of sensible starter rules based on layer and partition columns
  const partitionRules = partitionCols
    .map(
      (col) => `
  - name: not_null_${col.toLowerCase()}
    type: not_null
    column: ${col}
    severity: critical
    description: Partition column must never be null.`
    )
    .join("\n");

  const layerRules =
    layer === "silver" || layer === "gold"
      ? `
  # ---------------------------------------------------------------------------
  # Uniqueness
  # ---------------------------------------------------------------------------
  - name: row_count_positive
    type: row_count
    min: 1
    severity: critical
    description: Table must contain at least one row per partition.

  # ---------------------------------------------------------------------------
  # Freshness (add threshold appropriate for your schedule)
  # ---------------------------------------------------------------------------
  # - name: freshness_check
  #   type: max_staleness_hours
  #   column: _processed_at
  #   max_hours: 25
  #   severity: warning`
      : `
  # ---------------------------------------------------------------------------
  # Row count
  # ---------------------------------------------------------------------------
  - name: row_count_positive
    type: row_count
    min: 1
    severity: critical
    description: Bronze partition must contain at least one row.`;

  return `# DQ rules for ${manifest.name} — edit this file to add domain rules
# Generated by: forge generate --job ${manifest.name}
# Applied by:   forge_dq @track decorator inside ${manifest.name}.py
#
# Severity levels:
#   critical — job fails on violation (fail_fast=${manifest.dq?.failFast !== false ? "true" : "false"})
#   warning  — logged and continued; never fails the job
#
# Rule types supported by forge_dq:
#   not_null, row_count, unique, accepted_values,
#   min_value, max_value, regex, custom_sql, max_staleness_hours

version: "v1"
dataset: "${table}"
description: "Quality rules for ${manifest.name}"
owner: data-engineering
tags: [${[manifest.layer, manifest.name, ...(manifest.tags ?? [])].map((t) => `"${t}"`).join(", ")}]

rules:

  # ---------------------------------------------------------------------------
  # Completeness — partition columns
  # ---------------------------------------------------------------------------
${partitionRules}
${layerRules}

  # ---------------------------------------------------------------------------
  # TODO: add domain-specific rules below
  # ---------------------------------------------------------------------------
  # Example:
  # - name: status_accepted_values
  #   type: accepted_values
  #   column: status
  #   values: [pending, confirmed, shipped, delivered, cancelled]
  #   severity: warning
`;
}
