/**
 * Forge CLI — DQ Rules YAML Generator
 *
 * Produces a Data Quality rules YAML from inline rules defined in the manifest.
 * The output matches the format used by the Forge DQ framework (forge_dq DQRunner).
 *
 * Two entry points:
 *   generateDqYaml(manifest) — writes a full YAML file with header comments;
 *                              useful as documentation / audit artifact.
 *   rulesAsYaml(manifest)    — returns a compact YAML snippet of the rules array
 *                              only; used by dag.ts to embed inline rules in the
 *                              DQ gate SparkApplication YAML (base64-encoded).
 */
import type { ForgeJobManifest } from "../schema.js";

type DqRule = NonNullable<ForgeJobManifest["dq"]>["rules"][number];

/**
 * Render a single DQ rule as YAML lines (2-space indent relative to the
 * `rules:` list; each item starts with `- name:`).
 */
function renderRule(rule: DqRule): string {
  const lines: string[] = [
    `  - name: ${rule.name}`,
    `    type: ${rule.type}`,
  ];
  if (rule.column !== undefined)      lines.push(`    column: ${rule.column}`);
  if (rule.min !== undefined)         lines.push(`    min: ${rule.min}`);
  if (rule.max !== undefined)         lines.push(`    max: ${rule.max}`);
  if (rule.values !== undefined && rule.values.length > 0) {
    lines.push(`    values: [${rule.values.map((v) => `"${v}"`).join(", ")}]`);
  }
  lines.push(`    severity: ${rule.severity ?? "critical"}`);
  if (rule.description !== undefined) lines.push(`    description: "${rule.description}"`);
  return lines.join("\n");
}

/**
 * Return a compact YAML snippet containing only the `rules:` array.
 * Used by dag.ts to embed inline rules in the DQ gate task (base64-encoded).
 *
 * Returns an empty string if the manifest has no inline DQ rules.
 */
export function rulesAsYaml(manifest: ForgeJobManifest): string {
  const rules = manifest.dq?.rules;
  if (!rules || rules.length === 0) return "";
  return `rules:\n${rules.map(renderRule).join("\n")}`;
}

/**
 * Generate a full DQ YAML rules file from a manifest that uses inline rules.
 *
 * @param manifest Validated ForgeJobManifest (must have `dq.rules` set as an array)
 * @returns YAML string ready to write to disk, or empty string if no rules.
 */
export function generateDqYaml(manifest: ForgeJobManifest): string {
  const rules = manifest.dq?.rules;
  if (!rules || rules.length === 0) return "";

  const table =
    manifest.output.table ??
    `lakehouse.${manifest.layer}.${manifest.output.path.assetName
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "")}`;

  const failFastStr = manifest.dq?.failFast !== false ? "true" : "false";

  const rulesYaml = rules.map(renderRule).join("\n");

  return `# DQ rules for ${manifest.name} — generated from inline manifest rules
# Generated by: forge generate --job ${manifest.name}
# Applied by:   forge_dq DQRunner inside the dq_gate_${manifest.layer} Spark task
#
# Severity levels:
#   critical — job fails on violation (fail_fast=${failFastStr})
#   warning  — logged and continued; never fails the job
#
# Rule types supported by forge_dq:
#   not_null, row_count, unique, accepted_values,
#   min_value, max_value, regex, custom_sql, max_staleness_hours

version: "v1"
dataset: "${table}"
description: "Quality rules for ${manifest.name}"
owner: data-engineering
tags: [${[manifest.layer, manifest.name, ...(manifest.tags ?? [])].map((t) => `"${t}"`).join(", ")}]

rules:
${rulesYaml}
`;
}
